version: '3'
services: 
  
  mysqlsrv:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=aws-projecta-db
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - mysql-compose-network
      
networks: 
  mysql-compose-network:
    driver: bridge

volumes: 
  mysql_db: